name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
        with:
          lake-package-directory: console
      - uses: leanprover/lean-action@v1
        with:
          lake-package-directory: datatypes
      - uses: leanprover/lean-action@v1
        with:
          lake-package-directory: files
      - uses: leanprover/lean-action@v1
        with:
          lake-package-directory: functions
      - uses: leanprover/lean-action@v1
        with:
          lake-package-directory: json
